# encoding: utf-8


Country.delete_all
#Country.create(:id=>1,:iso=>"AD",:name=>"Andorra")
connection = ActiveRecord::Base.connection();
connection.execute("
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (1,'Andorra','Андорра','AD',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (2,'United Arab Emirates','Объединенные Арабские Эмираты','AE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (3,'Antigua and Barbuda','Антигуа и Барбуда','AG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (4,'Anguilla','Ангилья','AI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (5,'Albania','Албания','AL',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (6,'Armenia','Армения','AM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (7,'Netherland Antilles','Антильские Острова','AN',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (8,'Angola','Ангола','AO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (9,'Antarctica','Антарктика','AQ',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (10,'Argentina','Аргентина','AR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (11,'American Samoa','Американское Самоа','AS',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (12,'Austria','Австрия','AT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (13,'Australia','Австралия','AU',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (14,'Aruba','Аруба','AW',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (15,'Azerbaijan','Азербайджан','AZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (16,'Bosnia-Herzegovina','Босния и Герцеговина','BA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (17,'Barbados','Барбадос','BB',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (18,'Bangladesh','Бангладеш','BD',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (19,'Belgium','Бельгия','BE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (20,'Burkina Faso','Буркина-Фасо','BF',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (21,'Bulgaria','Болгария','BG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (22,'Bahrain','Бахрейн','BH',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (23,'Burundi','Бурунди','BI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (24,'Benin','Бенин','BJ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (25,'Bermuda','Бермудские Острова','BM',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (26,'Brunei Darussalam','Бруней','BN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (27,'Bolivia','Боливия','BO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (28,'Brazil','Бразилия','BR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (29,'Bahamas','Багамские Острова','BS',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (30,'Buthan','Бутан','BT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (31,'Bouvet Island','Буве','BV',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (32,'Botswana','Ботсвана','BW',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (33,'Belarus','Беларусь','BY',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (34,'Belize','Белиз','BZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (35,'Canada','Канада','CA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (36,'Cocos (Keeling) Isl.','Кокосовые Острова','CC',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (37,'Central African Rep.','Центральноафриканская Республика','CF',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (38,'Republic of the Congo','Республика Конго','CG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (39,'Switzerland','Швейцария','CH',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (40,'Ivory Coast','Кот-д\`Ивуар','CI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (41,'Cook Islands','Кука острова','CK',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (42,'Chile','Чили','CL',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (43,'Cameroon','Камерун','CM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (44,'China','Китай','CN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (45,'Colombia','Колумбия','CO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (46,'Costa Rica','Коста-Рика','CR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (47,'Democratic Republic of the Congo','Конго, Демократическая Республика','CD',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (48,'Cuba','Куба','CU',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (49,'Cape Verde','Кабо-Верде','CV',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (50,'Christmas Island','Остров Рождества','CX',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (51,'Cyprus','Кипр','CY',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (52,'Czech Republic','Чехия','CZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (53,'Germany','Германия','DE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (54,'Djibouti','Джибути','DJ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (55,'Denmark','Дания','DK',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (56,'Dominica','Доминика','DM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (57,'Dominican Republic','Доминиканская Республика','DO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (58,'Algeria','Алжир','DZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (59,'Ecuador','Эквадор','EC',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (60,'Estonia','Эстония','EE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (61,'Egypt','Египет','EG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (62,'Western Sahara','Западная Сахара','EH',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (63,'Spain','Испания','ES',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (64,'Ethiopia','Эфиопия','ET',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (65,'Finland','Финляндия','FI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (66,'Fiji','Фиджи','FJ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (67,'Falkland Islands','Фолклендские (Мальвинские) острова','FK',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (68,'Micronesia','Микронезия','FM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (69,'Faroe Islands','Фарерские Острова','FO',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (70,'France','Франция','FR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (71,'French Polynesia','Французская Полинезия','PF',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (72,'Gabon','Габон','GA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (73,'United Kingdom (Great Britain)','Великобритания','GB',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (74,'Grenada','Гренада','GD',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (75,'Georgia','Грузия','GE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (76,'Guyana (Fr.)','Гайана','GF',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (77,'Ghana','Гана','GH',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (78,'Gibraltar','Гибралтар','GI',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (79,'Greenland','Гренландия','GL',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (80,'Gambia','Гамбия','GM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (81,'Guinea','Гвинея','GN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (82,'Guadeloupe (Fr.)','Гваделупа','GP',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (83,'Equatorial Guinea','Экваториальная Гвинея','GQ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (84,'Greece','Греция','GR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (85,'Guatemala','Гватемала','GT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (86,'Guam (US)','Гуам','GU',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (87,'Guinea Bissau','Гвинея-Бисау','GW',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (88,'Guyana','Гвиана','GY',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (89,'Hong Kong','Гонконг','HK',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (90,'Heard Island and McDonald Islands','Острова Херд и Макдональд','HM',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (91,'Honduras','Гондурас','HN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (92,'Croatia','Хорватия','HR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (93,'Haiti','Гаити','HT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (94,'Hungary','Венгрия','HU',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (95,'Indonesia','Индонезия','ID',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (96,'Ireland','Ирландия','IE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (97,'Israel','Израиль','IL',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (98,'India','Индия','IN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (100,'Iraq','Ирак','IQ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (101,'Iran','Иран','IR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (102,'Iceland','Исландия','IS',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (103,'Italy','Италия','IT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (104,'Jamaica','Ямайка','JM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (105,'Jordan','Иордания','JO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (106,'Japan','Япония','JP',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (107,'Kenya','Кения','KE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (108,'Kirgistan','Кыргызстан','KG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (109,'Cambodia','Камбоджа','KH',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (110,'Kiribati','Кирибати','KI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (111,'Comoros','Коморские Острова','KM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (112,'St.Kitts Nevis Anguilla','Сент-Киттс и Невис','KN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (113,'Korea (North)','Корея (Северная)','KP',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (114,'Korea (South)','Корея (Южная)','KR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (115,'Kuwait','Кувейт','KW',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (116,'Cayman Islands','Каймановы Острова','KY',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (117,'Kazachstan','Казахстан','KZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (118,'Laos','Лаос','LA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (119,'Lebanon','Ливан','LB',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (120,'Saint Lucia','Сент-Люсия','LC',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (121,'Liechtenstein','Лихтенштейн','LI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (122,'Sri Lanka','Шри-Ланка','LK',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (123,'Liberia','Либерия','LR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (124,'Lesotho','Лесото','LS',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (125,'Lithuania','Литва','LT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (126,'Luxembourg','Люксембург','LU',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (127,'Latvia','Латвия','LV',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (128,'Libya','Ливия','LY',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (129,'Morocco','Морокко','MA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (130,'Monaco','Монако','MC',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (131,'Moldavia','Молдова','MD',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (132,'Madagascar','Мадагаскар','MG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (133,'Marshall Islands','Маршалловы Острова','MH',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (134,'Mali','Мали','ML',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (135,'Myanmar','Мьянма','MM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (136,'Mongolia','Монголия','MN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (137,'Macau','Аомынь','MO',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (138,'Northern Mariana Isl.','Северные Марианские острова','MP',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (139,'Martinique (Fr.)','Мартиника','MQ',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (140,'Mauritania','Мавритания','MR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (141,'Montserrat','Монтсеррат','MS',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (142,'Malta','Мальта','MT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (143,'Mauritius','Маврикий','MU',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (144,'Maldives','Мальдивы','MV',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (145,'Malawi','Малави','MW',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (146,'Mexico','Мексика','MX',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (147,'Malaysia','Малайзия','MY',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (148,'Mozambique','Мозамбик','MZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (149,'Namibia','Намибия','NA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (150,'New Caledonia (Fr.)','Новая Каледония','NC',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (151,'Niger','Нигер','NE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (152,'Norfolk Island','Норфолк','NF',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (153,'Nigeria','Нигерия','NG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (154,'Nicaragua','Никарагуа','NI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (155,'Netherlands','Нидерланды','NL',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (156,'Norway','Норвегия','NO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (157,'Nepal','Непал','NP',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (158,'Nauru','Науру','NR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (160,'Niue','Ниуэ','NU',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (161,'New Zealand','Новая Зеландия','NZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (162,'Oman','Оман','OM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (163,'Panama','Панама','PA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (164,'Peru','Перу','PE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (165,'French Southern and Antarctic Lands','Французские Южные и Антарктические Территории','TF',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (166,'Papua New','Папуа — Новая Гвинея','PG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (167,'Philippines','Филиппины','PH',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (168,'Pakistan','Пакистан','PK',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (169,'Poland','Польша','PL',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (170,'St. Pierre & Miquelon','Сен-Пьер и Микелон','PM',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (171,'Pitcairn','Питкэрн','PN',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (172,'Puerto Rico','Пуэрто-Рико','PR',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (173,'Portugal','Португалия','PT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (174,'Palau','Палау','PW',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (175,'Paraguay','Парагвай','PY',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (176,'Qatar','Катар','QA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (177,'Reunion (Fr.)','Реюньон','RE',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (178,'Romania','Румыния','RO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (179,'Russia','Россия','RU',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (180,'Rwanda','Руанда','RW',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (181,'Saudi Arabia','Саудовская Аравия','SA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (182,'Solomon Islands','Соломоновы Острова','SB',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (183,'Seychelles','Сейшельские острова','SC',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (184,'Sudan','Судан','SD',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (185,'Sweden','Швеция','SE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (186,'Singapore','Сингапур','SG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (187,'St. Helena','Остров Святой Елены','SH',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (188,'Slovenia','Словения','SI',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (189,'Svalbard & Jan Mayen Is','Свальбард','SJ',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (190,'Slovak Republic','Словакия','SK',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (191,'Sierra Leone','Сьерра-Леоне','SL',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (192,'San Marino','Сан-Марино','SM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (193,'Senegal','Сенегал','SN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (194,'Somalia','Сомали','SO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (195,'Suriname','Суринам','SR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (196,'St. Tome and Principe','Сан-Томе и Принсипи','ST',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (197,'El Salvador','Сальвадор','SV',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (198,'Syria','Сирия','SY',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (199,'Swaziland','Свазиленд','SZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (200,'Turks and Caicos Islands','Тёркс и Кайкос','TC',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (201,'Chad','Чад','TD',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (203,'Togo','Того','TG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (204,'Thailand','Таиланд','TH',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (205,'Tadjikistan','Таджикистан','TJ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (206,'Tokelau','Токелау','TK',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (207,'Turkmenistan','Туркменистан','TM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (208,'Tunisia','Тунис','TN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (209,'Tonga','Тонга','TO',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (210,'East Timor','Восточный Тимор','TP',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (211,'Turkey','Турция','TR',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (212,'Trinidad & Tobago','Тринидад и Тобаго','TT',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (213,'Tuvalu','Тувалу','TV',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (214,'Taiwan','Тайвань','TW',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (215,'Tanzania','Танзания','TZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (216,'Ukraine','Украина','UA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (217,'Uganda','Уганда','UG',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (218,'United States Minor Outlying Islands','Внешние малые острова (США)','UM',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (219,'United States','Соединенные Штаты Америки','US',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (220,'Uruguay','Уругвай','UY',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (221,'Uzbekistan','Узбекистан','UZ',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (222,'Vatican City State','Ватикан','VA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (223,'St.Vincent & Grenadines','Сент-Винсент и Гренадины','VC',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (224,'Venezuela','Венесуэла','VE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (225,'Virgin Islands (British)','Виргинские Острова (Британские)','VG',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (226,'Virgin Islands (US)','Виргинские Острова (США)','VI',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (227,'Vietnam','Вьетнам','VN',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (228,'Vanuatu','Вануату','VU',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (229,'Wallis & Futuna Islands','Острова Уоллис и Футуна','WF',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (230,'Samoa','Самоа','WS',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (231,'Yemen','Йемен','YE',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (232,'Montenegro','Черногория','ME',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (233,'South Africa','Южно-Африканская Республика','ZA',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (234,'Zambia','Замбия','ZM',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (235,'Serbia','Сербия','RS',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (236,'Zimbabwe','Зимбабве','ZW',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (238,'Abkhazia','Абхазия','',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (239,'Azores','Азорские острова','PT',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (240,'Åland Islands','Аландские острова','AX',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (241,'Afghanistan','Афганистан','AF',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (242,'British Indian Ocean Territory','Британская территория в Индийском океане','IO',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (243,'Guernsey','Гернси','GG',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (244,'Jersey','Джерси','JE',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (245,'Kosovo','Косово','',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (246,'Mayotte','Майотта','YT',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (247,'Republic of Macedonia','Македония','MK',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (248,'Isle of Man','Остров Мэн','IM',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (249,'Nagorno-Karabakh Republic','Нагорно-Карабахская Республика','',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (250,'Palestine','Палестина','PS',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (251,'Transnistria','Приднестровье','',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (252,'Northern Cyprus','Турецкая Республика Северного Кипра','NC',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (253,'Republic of Somaliland','Сомалиленд','',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (254,'Tamil Eelam','Тамил-Илам','',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (255,'Eritrea','Эритрея','ER',0,1);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (256,'South Georgia and the South Sandwich Islands','Южная Георгия и Южные Сандвичевы острова','GS',0,0);
INSERT INTO countries (id,name_en,name,iso,_order,independent) VALUES (257,'South Ossetia','Южная Осетия','',0,0);
");